### PR TITLE
Fix endif in mini.c

### PR DESCRIPTION
**Pull request by Minipada**
There is a double endif here and it can't compile. I'm not deep into the ethercat topic so it would be great to check.

Thanks a lot!

### CODE REVIEW

**Comment by ribalda** [comment]
Hi.

Thanks for your patch. For some reason my public copy in github has diversed what I use at work. Sorry about that. 

Can you try the content of this branch? https://github.com/ribalda/ethercat/tree/fix-ifdef

Your patch looks good to me, but I prefer to be on sync with the code that we use in production.

**Comment by Minipada** [comment]
Hi,

Not an issue. I just built your branch and it compiled well. Taking a look at it, I now wonder if the first `#endif` should actually be a `#else` like it is on your branch instead of simply being removed.

**Comment by Minipada** [comment]
@ribalda should this be merged?

**Comment by ribalda** [comment]
done, thanks for the ping :)

**Pull request closed without merging**
